/*
 * Semaforo.java
 */
package net.ausiasmarch.semaforo.modelo;

/**
 *
 * @author Administrador
 */
public class Semaforo extends javax.swing.JPanel {

    //Propiedades
    private ColorSemaforo estado;
    private Thread hiloCambioColor = null;
    private boolean stop;
    private int duracion;
    private int parpadeos;

    //Constructor
    public Semaforo() {
        initComponents();
        estado = ColorSemaforo.ROJO;
        duracion = 1500;
        parpadeos = 5;
    }

    //Metodos para cambiar el estado del color y el jLabel visible
    public void setRojo() {
        estado = ColorSemaforo.ROJO;
        jLabelRojo.setVisible(true);
        jLabelAmbar.setVisible(false);
        jLabelVerde.setVisible(false);
        jLabelSemaforo.setVisible(false);
    }

    public void setAmbar() {
        estado = ColorSemaforo.AMBAR;
        jLabelRojo.setVisible(false);
        jLabelAmbar.setVisible(true);
        jLabelVerde.setVisible(false);
        jLabelSemaforo.setVisible(false);
    }

    public void setVerde() {
        estado = ColorSemaforo.VERDE;
        jLabelRojo.setVisible(false);
        jLabelAmbar.setVisible(false);
        jLabelVerde.setVisible(true);
        jLabelSemaforo.setVisible(false);
    }

    // Obtiene el estado del semaforo, devuelve un enumerado
    public ColorSemaforo getEstado() {
        return estado;
    }

    //Metodo para apagar el semaforo
    public void apagado() {
        jLabelRojo.setVisible(false);
        jLabelAmbar.setVisible(false);
        jLabelVerde.setVisible(false);
        jLabelSemaforo.setVisible(true);
    }

    //Metodo para cambiar el color del semaforo segun en que estado se encuentre
    public void cambiaColor() {
        switch (estado) {
            case ROJO:
                setVerde();
                break;
            case VERDE:
                setAmbar();
                break;
            case AMBAR:
                setRojo();
                break;
        }
    }

    // Metodo para dormir el hilo
    private void pausa(int num) {
        try {
            Thread.sleep(num);
        } catch (InterruptedException ex) {
            throw new RuntimeException(ex);
        }
    }

    /* Creamos un metodo PARPADEAR para que parpadee el semaforo*/
    private void parpadea() {
        for (int i = 0; i < parpadeos; i++) {
            if (stop) {
                break;
            }
            apagado();
            if (stop) {
                break;
            }
            pausa(200);
            if (stop) {
                break;
            }
            setAmbar();
            if (stop) {
                break;
            }
            pausa(200);
        }
    }

    //Metodos Get y set
    public int getDuracion() {
        return duracion;
    }

    public void setDuracion(int duracion) {
        this.duracion = duracion;
    }

    public int getParpadeos() {
        return parpadeos;
    }

    public void setParpadeos(int parpadeos) {
        this.parpadeos = parpadeos;
    }

    //Creamos metodo INICIAR que va a tener una clase interna ANONIMA 
    public void iniciar() {
        hiloCambioColor = new Thread() {
            @Override
            public void run() {
                while (!stop) {
                    cambiaColor();
                    pausa(estado.getValue() * duracion);
                    if (estado == ColorSemaforo.AMBAR) {
                        parpadea();
                    }
                }
            }
        };
        //FIN CLASE ANIDADA
        hiloCambioColor.start();
        stop = false;
    }

    /* Creamos metodo PARAR que luego llamaremos desde el MAIN*/
    public void parar() {
        stop = true;
        hiloCambioColor = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSemaforo = new javax.swing.JLabel();
        jLabelRojo = new javax.swing.JLabel();
        jLabelVerde = new javax.swing.JLabel();
        jLabelAmbar = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSemaforo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/semaforo/img/semaforoOff.png"))); // NOI18N
        add(jLabelSemaforo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 460));

        jLabelRojo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/semaforo/img/semaforoRojo.png"))); // NOI18N
        add(jLabelRojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 460));

        jLabelVerde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/semaforo/img/semaforoVerde.png"))); // NOI18N
        add(jLabelVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 460));

        jLabelAmbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/semaforo/img/semaforoAmbar.png"))); // NOI18N
        add(jLabelAmbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 460));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAmbar;
    private javax.swing.JLabel jLabelRojo;
    private javax.swing.JLabel jLabelSemaforo;
    private javax.swing.JLabel jLabelVerde;
    // End of variables declaration//GEN-END:variables
}
