/*
 * Semaforo.java
 */
package net.ausiasmarch.semaforo.modelo;

/**
 *
 * @author  Administrador
 */
public class Semaforo extends javax.swing.JPanel {

    public Semaforo() {
        initComponents();


    }

 
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSemaforo = new javax.swing.JLabel();
        jLabelRojo = new javax.swing.JLabel();
        jLabelVerde = new javax.swing.JLabel();
        jLabelAmbar = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSemaforo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/semaforo/img/semaforoOff.png"))); // NOI18N
        add(jLabelSemaforo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 460));

        jLabelRojo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/semaforo/img/semaforoRojo.png"))); // NOI18N
        add(jLabelRojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 460));

        jLabelVerde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/semaforo/img/semaforoVerde.png"))); // NOI18N
        add(jLabelVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 460));

        jLabelAmbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/semaforo/img/semaforoAmbar.png"))); // NOI18N
        add(jLabelAmbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 460));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAmbar;
    private javax.swing.JLabel jLabelRojo;
    private javax.swing.JLabel jLabelSemaforo;
    private javax.swing.JLabel jLabelVerde;
    // End of variables declaration//GEN-END:variables
}
